name: 'Build'
run-name: 'Build Package'
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node v16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm ci

      - name: Pull Keycloak Image
        run: docker pull quay.io/keycloak/keycloak:latest

      - name: Test Package
        run: npm run test

      - name: Build Package
        run: npm run build
